name: Build / Publish Wiki

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Install
        run: |
          npm ci --ignore-scripts
          npm run postinstall:defs

      - name: Build
        run: |
          gulp
          gulp prettier

      - name: Check output files
        run: |
          ls out
          ls out/docs

      - name: Publish to Wiki
        uses: OrlovM/Wiki-Action@v1
        with:
          path: "out/docs"
          token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
