name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Install
        run: |
          npm ci --ignore-scripts
          npm run postinstall:defs

      - name: Build
        run: |
          gulp ci

      - name: Push changes to wiki repo
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
        with:
          source-directory: out/docs
          destination-github-username: vladzaharia
          destination-repository-name: bitburner.wiki
          user-email: service@vlad.gg
          user-name: Service Account
          target-branch: master
