name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Install
        run: |
          npm ci --ignore-scripts
          npm run postinstall:defs

      - name: Build
        run: |
          gulp ci

      - name: Push Wiki Changes
        uses: Andrew-Chen-Wang/github-wiki-action@v3
        env:
          WIKI_DIR: out/docs
          GH_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          GH_MAIL: hey@vlad.gg
          GH_NAME: ${{ github.repository_owner }}
