name: Publish Wiki

on:
    push:
        branches: [main]

jobs:
    publish:
        runs-on: ubuntu-latest
        environment: production

        steps:
            - name: Wait for build to succeed
              id: wait-for-build
              uses: fountainhead/action-wait-for-check@v1.0.0
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  checkName: build

            - name: Fail if build not successful
              run: exit 1
              if: ${{ steps.wait-for-build.outputs.conclusion != 'success' }}

            - name: Download build artifact
              uses: dawidd6/action-download-artifact@v2
              with:
                  workflow: build.yml
                  workflow_conclusion: success
                  branch: ${{ github.ref }}
                  name: artifact
                  path: out
                  check_artifacts: true
              if: ${{ steps.wait-for-build.outputs.conclusion == 'success' }}

            - name: Push Wiki Changes
              uses: Andrew-Chen-Wang/github-wiki-action@v3
              env:
                  WIKI_DIR: out/docs
                  GH_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
                  GH_MAIL: hey@vlad.gg
                  GH_NAME: ${{ github.repository_owner }}
                  WIKI_PUSH_MESSAGE: Wiki docs update
                  if: ${{ steps.wait-for-build.outputs.conclusion == 'success' }}
