name: Publish Wiki

on:
    push:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest
        environment: production

        steps:
            - name: Download build artifact
              uses: dawidd6/action-download-artifact@v2
              with:
                  workflow: build.yml
                  workflow_conclusion: success
                  branch: main
                  name: artifact
                  path: out
                  check_artifacts: true

            - name: Push Wiki Changes
              uses: Andrew-Chen-Wang/github-wiki-action@v3
              env:
                  WIKI_DIR: out/docs
                  GH_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
                  GH_MAIL: hey@vlad.gg
                  GH_NAME: ${{ github.repository_owner }}
